export enum ProfileStatus {
	MINE = 'MINE',
	FRIEND = 'FRIEND',
	REQUESTEDBYME = 'REQUESTEDBYME',
	REQUESTEDBYOTHER = 'REQUESTEDBYOTHER',
	BLOCKEDBYME = 'BLOCKEDBYME',
	BLOCKEDBYOTHER = 'BLOCKEDBYOTHER',
	UNKNOWN = 'UNKNOWN', // 탈퇴한 유저. 없는 유저. 내가 차단당한 유저일때
	UNDEFINED = 'UNDEFINED',
}
